name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Remove old ChromeDriver
        run: |
          sudo rm -f /usr/bin/chromedriver
          echo "Old ChromeDriver removed"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start application
        run: |
          nohup java -jar artifacts/app-replan-delivery.jar &
          sleep 5

      - name: Build with Gradle
        run: ./gradlew test --info

      - name: Stop application
        run: pkill -f "app-replan-delivery.jar"

      - name: Build with Gradle
        run: ./gradlew test --info

      - name: Stop application
        run: pkill -f "app-replan-delivery.jar"